--TEAM
CREATE TABLE TEAM2(
    TEAMID NUMBER(8) CONSTRAINT PK_TEAM_ID PRIMARY KEY,
    RESIONNAME VARCHAR2(20),
    TEAMNAME VARCHAR2(30) NOT NULL,
    STARTDATE DATE,
    TEL VARCHAR2(20),
    HOMEPAGE VARCHAR2(30)
);

--PLAYER
CREATE TABLE PLAYER2(
    PLAYERID NUMBER CONSTRAINT PK_PLAYER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    JOINDATE DATE,
    POSITION VARCHAR2(20),
    HEIGHT NUMBER(5,1),
    TEAMID NUMBER(8)
);

ALTER TABLE PLAYER2
ADD
CONSTRAINT FK_TEAM_ID FOREIGN KEY(TEAMID)
REFERENCES TEAM2(TEAMID);

--팀추가
INSERT INTO team2(TEAMID, RESIONNAME, TEAMNAME, STARTDATE, TEL, HOMEPAGE)
VALUES(1000,'서울','베어즈',SYSDATE,'02-123-4567','http://www.bears.com');
INSERT INTO team2(TEAMID, RESIONNAME, TEAMNAME, STARTDATE, TEL, HOMEPAGE)
VALUES(2000,'대구','라이온즈','93/04/11','031-123-4567','http://www.lions.com');
--선수추가
INSERT INTO PLAYER2(PLAYERID, NAME, JOINDATE,POSITION, HEIGHT, TEAMID)
VALUES(100,'홍길동',to_DATE('2020/09/12 09:12:35','YYYY/MM/DD HH/MI/ss'),'투수',181.1,1000);

INSERT INTO PLAYER2(PLAYERID, NAME, JOINDATE,POSITION, HEIGHT, TEAMID)
VALUES(200,'성춘향',to_DATE('2020/06/12 09:12:35','YYYY/MM/DD HH/MI/ss'),'1루수',165.3,2000);

INSERT INTO PLAYER2(PLAYERID, NAME, JOINDATE,POSITION, HEIGHT, TEAMID)
VALUES(300,'일지매',to_DATE('2020/04/23 09:12:35','YYYY/MM/DD HH/MI/ss'),'좌익수',178,'');

SELECT p.playerid,name, p.teamid, t.teamid, t.teamname, t.homepage
FROM TEAM2 t , PLAYER2 p
WHERE name = '홍길동'
AND p.position = '투수'
and p.teamid=t.teamid;

---------------------------------------------------------------
CREATE TABLE PRODUCT2 (
    PRODUCTID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50)NOT NULL,
    PRICE NUMBER,
    PRODUCT_DESC VARCHAR2(500)
);

CREATE TABLE CONSUMER2 (
    USERID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(50)NOT NULL,
    AGE VARCHAR2(50)
);

CREATE TABLE CART2 (
    CARTID VARCHAR2(50) primary key,
    USERID VARCHAR2(50),	--외래키
    PRODUCTID VARCHAR2(50),	--왜래키
    AMOUNT VARCHAR2(50)
);

ALTER TABLE CART2
ADD
CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCTID)
REFERENCES PRODUCT2(PRODUCTID);

ALTER TABLE CART2
ADD
CONSTRAINT FK_CONSUMER_ID FOREIGN KEY (USERID)
REFERENCES CONSUMER2(USERID);

--상품을 등록
INSERT INTO PRODUCT2(PRODUCTID, NAME, PRICE, PRODUCT_DESC)
VALUES(1001,'새우깡',1500,'맛있어요');

INSERT INTO PRODUCT2(PRODUCTID, NAME, PRICE, PRODUCT_DESC)
VALUES(1002,'포테이토칩',2400,'감자맛');

INSERT INTO PRODUCT2(PRODUCTID, NAME, PRICE, PRODUCT_DESC)
VALUES(1003,'카누',5500,'인스턴트커피');

--소비자를 등록
INSERT INTO CONSUMER2(USERID, NAME, AGE)
VALUES ('HGD','홍길동','24');

INSERT INTO CONSUMER2(USERID, NAME, AGE)
VALUES ('SCH','성춘향','16');

--쇼핑 등록
INSERT INTO CART2(CARTID, USERID, PRODUCTID, AMOUNT)
VALUES (1,'SCH','1003',2);

INSERT INTO CART2(CARTID, USERID, PRODUCTID, AMOUNT)
VALUES (2,'SCH','1001',1);

INSERT INTO CART2(CARTID, USERID, PRODUCTID, AMOUNT)
VALUES (3,'HGD','1002',3);

SELECT *
FROM CART2
WHERE USERID = 'SCH';

SELECT c.userid,c.productid,p.name,p.price
FROM CART2 c, PRODUCT2 p
WHERE c.productID=p.productID and c.userid='sch';
